using DBapplication;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;

namespace PawPulse
{
    public partial class ShelterManageKennelsUC : UserControl
    {
        // 1. Instantiate your Controller
        Controller controllerObj = new Controller();

        public ShelterManageKennelsUC()
        {
            InitializeComponent();
        }

        private void ShelterManageKennelsUC_Load(object sender, EventArgs e)
        {
            // Populate the static status dropdown on load
            cmbStatus.Items.Clear();
            cmbStatus.Items.Add("Available");
            cmbStatus.Items.Add("Needs Cleaning");

            // Fetch the database data
            RefreshData();
        }

        // Helper method to reload both the grid and the dropdown so it's always up to date
        private void RefreshData()
        {
            // 1. Load the Grid using the Admin function
            dgvKennels.DataSource = controllerObj.GetAllKennelsWithAnimals();

            // 2. Load Dropdown with animals needing a home
            DataTable dtAnimals = controllerObj.GetUnassignedShelterAnimals();
            cmbUnassignedAnimals.DataSource = dtAnimals;
            cmbUnassignedAnimals.DisplayMember = "AnimalName";
            cmbUnassignedAnimals.ValueMember = "AnimalID";
            cmbUnassignedAnimals.SelectedIndex = -1;
        }

        // ASSIGN BUTTON
        private void btnAssign_Click(object sender, EventArgs e)
        {
            if (dgvKennels.SelectedRows.Count == 0 && dgvKennels.SelectedCells.Count == 0)
            {
                MessageBox.Show("Please select a Kennel from the grid.");
                return;
            }
            if (cmbUnassignedAnimals.SelectedIndex == -1)
            {
                MessageBox.Show("Please select an Animal from the dropdown.");
                return;
            }

            int rowIndex = dgvKennels.CurrentCell.RowIndex;
            int kennelId = Convert.ToInt32(dgvKennels.Rows[rowIndex].Cells["KennelID"].Value);
            int animalId = Convert.ToInt32(cmbUnassignedAnimals.SelectedValue);

            // Make sure the kennel isn't already occupied
            string currentStatus = dgvKennels.Rows[rowIndex].Cells["Status"].Value.ToString();
            if (currentStatus == "Occupied")
            {
                MessageBox.Show("This kennel is already occupied! Please select an empty one.");
                return;
            }

            if (controllerObj.AssignAnimalToKennel(animalId, kennelId) > 0)
            {
                MessageBox.Show("Animal assigned to kennel successfully.");
                RefreshData(); // Immediately update the UI
            }
        }

        // REMOVE BUTTON
        private void btnRemove_Click(object sender, EventArgs e)
        {
            if (dgvKennels.SelectedRows.Count == 0 && dgvKennels.SelectedCells.Count == 0)
            {
                MessageBox.Show("Please select a Kennel from the grid to clear.");
                return;
            }

            int rowIndex = dgvKennels.CurrentCell.RowIndex;

            // Check the "Occupied By" column generated by our SQL JOIN
            string occupiedBy = dgvKennels.Rows[rowIndex].Cells["Occupied By"].Value.ToString();

            if (occupiedBy == "Empty")
            {
                MessageBox.Show("This kennel is already empty.");
                return;
            }

            int kennelId = Convert.ToInt32(dgvKennels.Rows[rowIndex].Cells["KennelID"].Value);

            if (controllerObj.ClearKennel(kennelId) > 0)
            {
                MessageBox.Show("Animal removed. Kennel status set to 'Needs Cleaning'.");
                RefreshData();
            }
        }

        // UPDATE STATUS BUTTON
        private void btnUpdateStatus_Click(object sender, EventArgs e)
        {
            if (dgvKennels.SelectedRows.Count == 0 && dgvKennels.SelectedCells.Count == 0)
            {
                MessageBox.Show("Please select a Kennel from the grid to update.");
                return;
            }
            if (cmbStatus.SelectedIndex == -1)
            {
                MessageBox.Show("Please select a status (Available / Needs Cleaning).");
                return;
            }

            int rowIndex = dgvKennels.CurrentCell.RowIndex;
            int kennelId = Convert.ToInt32(dgvKennels.Rows[rowIndex].Cells["KennelID"].Value);
            string newStatus = cmbStatus.Text;
            string occupiedBy = dgvKennels.Rows[rowIndex].Cells["Occupied By"].Value.ToString();

            // Prevent marking a kennel with an animal inside it as "Available"
            if (occupiedBy != "Empty" && newStatus == "Available")
            {
                MessageBox.Show("You cannot mark an occupied kennel as Available.");
                return;
            }

            if (controllerObj.UpdateKennelStatus(kennelId, newStatus) > 0)
            {
                MessageBox.Show("Kennel status updated.");
                RefreshData();
                cmbStatus.SelectedIndex = -1;
            }
        }

        // Keep this so the Designer doesn't break, but it can stay empty
        private void cmbUnassignedAnimals_SelectedIndexChanged(object sender, EventArgs e)
        {

        }
    }
}